export const colors = {
  primary_color: '#6EB943',
  secondary_color: '#E7FFD9',
  darker_green_color: '#569E2C',
  black_color: '#333',
  dark_grey_color: '#8B8B8B',
  light_grey_color: '#F3F1F1',
  primary_information_text_color: '#4A4A4A',
  yellow_color: '#F8C40E',
  background_color: '#FAFAFA',
  secondary_information_text_color: '#C4C4C4',
  tab_color: '#D1D1D1',
  chat_item: '#F1F9ED',
  red_color: '#E15554',
};
